# 리스트 2-11 my_config.yml

COMMON: &COMMON
  author: "YAMADA, Yoshihiro"
  logo:
    source: "http://www.wings.msn.to/image/wings.jpg"
    width: 215
    height: 67

development:
  hoge: "dev"
  <<: *COMMON

test:
  hoge: "test"
  <<: *COMMON

production:
  hoge: "pro"
  <<: *COMMON
